"""
Django settings for aiapi project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0pm-@32ln=-)q)o3l$47n1_e0l-t(%e2yhlj$s%%2*fi73-y4k'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
    'diagnosis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aiapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'diagnosis/../templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aiapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

S3_SECRET_ID = 'LTAI5tMk3XXjea782mz5qFbM'
S3_SECRET_KEY = 'YYPg0YcUgQgYChKYaUTREVPewmwE14'
S3_ENDPOINT_URL = 'https://oss-cn-hongkong.aliyuncs.com'
S3_BUCKET = 'aspine-ai'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 指定 Broker 使用 Redis，Broker 负责任务的分发和调度
CELERY_BROKER_URL = 'redis://192.168.191.128:6379/0'
# 指定结果存储 Backend 使用 Redis，Backend 负责存储任务执行结果
CELERY_RESULT_BACKEND = 'redis://192.168.191.128:6379/1'
# # django-celery-results 设置
# CELERY_RESULT_BACKEND = 'django-db'
CELERY_IMPORTS = ('diagnosis.tasks', )
# 时区,与django的TIMEZONE一致
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_TASK_TRACK_STARTED = True
# # 有些情况防止死锁
CELERYD_FORCE_EXECV = True
# # 任务失败允许重试
CELERY_ACKS_LATE = True
# Worker并发数量，一般默认CPU核数，可以不设置
CELERY_WORKER_CONCURRENCY = 1  # CELERYD_CONCURRENCY = 4
# 每个worker最多执行的任务数，超过这个就将worker进行销毁，防止内存泄漏，默认无限
CELERYD_MAX_TASKS_PER_CHILD = 10
# # 单个任务运行的最大时间，超过这个时间，task就会被kill
CELERY_TASK_TIME_LIMIT = 20 * 1
# # 过期时间,默认一天
CELERY_RESULT_EXPIRES = 20 * 1

CVAT_URL = 'http://8.217.95.207:8080'
CVAT_USERNAME = 'admin'
CVAT_PASSWORD = '9na6JucPkzP9'
CVAT_IMG_FOLDER_PREFIX = 'ossfs/'

MODEL_DICT = {
    "Pivles": {
        "model": "Pivles_Densenet121",
        "img_height": 500,
        "img_width" : 280,
        "model_path" : "D:\/aspine\/densenet121.h5"
    },
    "SelfAssessAP10": {
        "model": "SelfAssessAP10_Yolov8",
        "img_height": 500,
        "img_width" : 280,
        "model_path": "D:\/aspine\/yolov8x-pose-p6.pt"
    },
    "SelfAssessLT5": {
        "model": "SelfAssessLT5_Yolov8",
        "img_height": 500,
        "img_width": 280,
        "model_path": "D:\/aspine\/yolov8x-pose-p6.pt"
    }
}

